---
# tasks file for update_os
- name: update RHEL-like
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"

- name: update Arch
  include_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"