---
- name: Install extension
  apt:
    name: gnupg2
    state: present
    update_cache: yes

- name: add gpg-key mongo
  apt_key:
    url: https://pgp.mongodb.com/server-{{ version_mongodb }}.asc
    state: present

- name: add mongodb repo
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/debian bookworm/mongodb-org/{{ version_mongodb }} main"
    state: present
    filename: mongodb-org-{{ version_mongodb }}

- name: Install mongodb
  apt:
    name: mongodb-org
    state: present
    update_cache: yes