---
# tasks file for mongodb
- name: Install mongod on Debian-like
  include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Install mongod on RHEL-like
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"

- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: true