---
# tasks file for mariadb
- name: Deploy MariaDB on RHEL
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"

- name: Deploy MariaDB on Arch
  include_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: True

- name: Update root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    login_unix_socket: "{{ mysql_socket }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: set .my.cnf file
  template:
    src: my.cnf
    dest: /root/.my.cnf
    mode: 0600

- name: Secure Installation
  block:

    - name: Delete anonymous MySQL user
      mysql_user:
        name: ""
        host: "{{ item }}"
        state: absent
      with_items:
        - localhost
        - "{{ ansible_nodename }}"

    - name: Delete hostname based MySQL user 
      mysql_user:
        name: root
        host: "{{ ansible_nodename }}"
        state: absent

    - name: Remove MySQL test database
      mysql_db:
        name: test
        state: absent
  when: secure_install == True

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  when: create_db == True

- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_pass }}" 
    priv: "{{ db_name }}.*:ALL,GRANT"
    host: localhost
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  when: create_user == True


