---
- name: add MariaDB repository
  yum_repository:
    name: MariaDB
    description: MariaDB repository
    file: MariaDB
    baseurl: https://rpm.mariadb.com/repo/mariadb-server/{{ version_MariaDB }}/yum/rhel/{{ ansible_distribution_major_version }}/$basearch
    gpgkey: https://downloads.mariadb.com/MariaDB/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    module_hotfixes: 1 # Need for AlmaLinux 8

- name: Install MariaDB
  dnf:
    name:
      - "MariaDB-server-{{ version_MariaDB }}"
      - "MariaDB-client-{{ version_MariaDB }}"
    state: latest
    update_cache: yes

- name: Install extension
  dnf:
    name:
      - python3-PyMySQL
    state: present
