---
- name: add MariaDB repository
  yum_repository:
    name: MariaDB
    description: MariaDB repository
    file: MariaDB
    baseurl: https://dlm.mariadb.com/repo/mariadb-server/{{ version_MariaDB }}/yum/rhel/$releasever/$basearch
    gpgkey: file:///etc/pki/rpm-gpg/MariaDB-MaxScale-GPG-KEY
    gpgcheck: yes
    module_hotfixes: 1 # Need for AlmaLinux 8

- name: Install MariaDB
  dnf:
    name:
      - MariaDB-server
      - MariaDB-client
    state: latest
    update_cache: yes

- name: Install extension
  dnf:
    name:
      - python3-PyMySQL
    state: present
