---
# tasks file for nginx
- name: Install Nginx on Arch-based
  include_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"

- name: Install Nginx on RHEL-like
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true