---
# tasks file for apache
- name: Fail when OS is unsupported
  fail:
    msg: "Unsupported OS family: {{ ansible_os_family }}"
  when: ansible_os_family not in ["RedHat", "Debian", "Archlinux"]

- name: Ensure Apache service is installed
  package:
    name: "{{ apache_package_name[ansible_os_family|lower] }}"
    state: present

- name: Ensure Apache is running
  service:
    name: "{{ apache_service_name[ansible_os_family|lower] }}"
    state: started
    enabled: true

- name: Ensure Apache is responding on port 80
  wait_for:
    port: 80
    timeout: 10
    delay: 5
    state: started

- name: Validate Apache configuration
  command: "{{ apache_ctl_command[ansible_os_family|lower] }}"
  register: apache_config_test
  failed_when: apache_config_test.rc != 0

- name: Restart Apache service 
  service:
    name: "{{ apache_service_name[ansible_os_family|lower] }}"
    state: restarted
  when: apache_config_test.rc == 0
  notify:
    - Restart Apache


