---
# tasks file for apache
- name: Deploy apache on RHEL
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"  

- name: Deploy apache on Arch
  include_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"

- name: Deploy apache on Debian/Ubuntu
  include_tasks: debian.yaml
  when: ansible_os_family == "Debian"
