---
# tasks file for java
- name: Install Java on Debian-like
  include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Install Java on RHEL-like
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"