- name: Install PHP
  pacman:
    name: php
    state: present
    update_cache: yes

- name: Install php-modules
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_modules }}"
  when: php_modules is defined