- name: Install PHP on Debian/Ubuntu
  apt:
    name: php
    state: present
    update_cache: yes

- name: Install PHP-modules
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_modules }}"
  when: php_modules is defined