---
# tasks file for php
- name: Deploy PHP on RHEL-based 
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"

- name: Set php.ini parametr
  block:
    - name: Set memory_limit
      lineinfile:
        path: /etc/php.ini
        regexp: 'memory_limit'
        line: "memory_limit = {{ php_memory_limit }}"
      when: php_memory_limit is defined
