---
# tasks file for php
- name: Deploy PHP on RHEL-based 
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"

- name: Deploy PHP on Arch-based
  include_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"

- name: Deploy PHP on Debian/Ubuntu
  include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Set php.ini parametrs
  block:
    - name: Set memory_limit
      lineinfile:
        path: "{{ php_ini_path }}"
        regexp: 'memory_limit'
        line: "memory_limit = {{ php_memory_limit }}"
      when: php_memory_limit is defined
      notify:
        - Restart PHP-FPM
        - Restart Apache2
