---
- name: Import key for Remi repo
  rpm_key:
    key: "http://rpms.remirepo.net/enterprise/{{ ansible_distribution_major_version }}/RPM-GPG-KEY-remi"
    state: present

- name: add remi repo for php
  dnf: 
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: Enable remi module for PHP
  command: dnf module enable php:remi-{{ php_version }} -y
  args: 
    creates: /etc/dnf/modules.d/php.module

- name: Install PHP-"{{ php_version }}"                     
  dnf:
    name: '@php:remi-{{ php_version }}'
    state: present

- name: Install PHP modules
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ php_modules }}"
  when: php_modules | length > 0