---
# tasks file for openlitespeed
- name: Deploy OpenLiteSpeed on Debian-like
  include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Deploy OpenLiteSpeed on RHEL-like
  include_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"

- name: Start and enable openlitespeed service
  service:
    name: lshttpd
    state: started
    enabled: true

- name: Validate listener_port
  assert:
    that: 
      - listener_port is defined
      - listener_port | int >= 1 and listener_port | int <= 65535
    msg: "listener_port must be a valid port (1-65535)"
  when: listener_port is defined

- name: Set default listener port
  lineinfile:
    path: /usr/local/lsws/conf/httpd_config.conf
    regexp: 'address                  \*:8088'
    line: '    address                  *:{{ listener_port }}'
  when: listener_port is defined
  notify: restart_openlitespeed
