---
# tasks file for openlitespeed
- name: Deploy OpenLiteSpeed on Debian-like
  include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Start and enable openlitespeed service
  service:
    name: lshttpd
    state: started
    enabled: true

- name: Set default listener port
  lineinfile:
    path: /usr/local/lsws/conf/httpd_config.conf
    regexp: 'address                  \*:8088'
    line: '    address                  *:{{ listener_port }}'
  when: listener_port is defined
  notify: restart_openlitespeed
