- name: Import key for Remi repo
  rpm_key:
    key: "http://rpms.remirepo.net/enterprise/{{ ansible_distribution_major_version }}/RPM-GPG-KEY-remi"
    state: present

- name: add remi repo for php
  dnf: 
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: add OpenLiteSpeed Repository
  yum_repository:
    name: litespeed
    description: OpenLiteSpeed repository
    file: litespeed
    baseurl: http://rpms.litespeedtech.com/centos/$releasever/$basearch
    gpgkey: http://rpms.litespeedtech.com/centos/RPM-GPG-KEY-litespeed
    gpgcheck: yes
    module_hotfixes: 1 # Need for AlmaLinux 8

- name: Install OpenLiteSpeed
  dnf:
    name: openlitespeed
    state: present
    update_cache: yes
    skip_broken: yes