---
# handlers file for php
- name: Restart PHP-FPM
  service:
    name: php-fpm
    state: restarted
  when: ansible_os_family != "Debian"

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"