---
# tasks file for consul
- name: Deploy consul on RHEL
  include_tasks: rhel.yml
  when: ansible_os_family =="RedHat"

- name: Take key for consul cluster
  shell: "consul keygen"
  register: key_consul  
  run_once: true

- name: delete old keyring
  shell: "rm -rf /opt/consul/serf/*.keyring"

- name: Set consul cluster
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644

- name: Start consul service
  service:
    name: consul
    state: started
    enabled: true

- name: Wait for Consul API to become available
  uri:
    url: "http://localhost:8500/v1/status/leader"
    method: GET
    status_code: 200
  register: consul_health
  retries: 5
  delay: 2
  until: consul_health.status == 200
  tags: [healthcheck]
